# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-08 16:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stix_id', models.CharField(default='identity--cc8c086b-a76e-46f1-826e-55644cad043b', max_length=100, unique=True)),
                ('image_url', models.CharField(default='Profile_Pic_default.png', max_length=75)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
